### ISSUE TITLE
license

### ISSUE THREAD

**Issue by gidden** [robintw/XArrayAndRasterio#1]
Hi @robintw!

This is awesome and great work! I was looking to do something exactly like this and am glad you've taken the time to do it before me =).

I'd like to use your code (and contribute any new features that make sense, etc.), but don't want to bring in another dependency. Would you be willing to add a license so that I can use this module directly (with appropriate attribution, of course!)?

Cheers!

**Comment by robintw** [comment]
Hi,

I've added a license now - I feel terribly embarrassed that I didn't have one originally. Please feel free to use the module however you want - and submit any issues or add any new features.

At some point I should get around to adding a `setup.py` and registering the module on PyPI so that it can be installed via `pip`, but I haven't had chance to do that yet (and I wanted to do a bit more testing before releasing it - even as a beta version).
